### ISSUE TITLE
raise TypeError(f"datetime64 type does not support {how} operations") TypeError: datetime64 type does not support sum operations

### ISSUE THREAD

**Issue by xinmans** [phammings/SPX500-Gamma-Exposure-Calculator#1]
bash gammaCalculator.sh 
``` 
Running Gamma Calculator...
use downloaded spx_quotedata.csv...
saved_plots contents cleared.
Creating Absolute Gamma Exposure and Gamma Profile Charts...
Traceback (most recent call last):
  File "/home/xinmans/mydev/SPX500-Gamma-Exposure-Calculator/modules/main.py", line 91, in <module>
    dfAgg = df.groupby(['StrikePrice']).sum()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xinmans/.local/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 2263, in sum
    result = self._agg_general(
             ^^^^^^^^^^^^^^^^^^
  File "/home/xinmans/.local/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1422, in _agg_general
    result = self._cython_agg_general(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xinmans/.local/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1507, in _cython_agg_general
    new_mgr = data.grouped_reduce(array_func)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xinmans/.local/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 1506, in grouped_reduce
    applied = blk.apply(func)
              ^^^^^^^^^^^^^^^
  File "/home/xinmans/.local/lib/python3.11/site-packages/pandas/core/internals/blocks.py", line 329, in apply
    result = func(self.values, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xinmans/.local/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1490, in array_func
    result = self.grouper._cython_operation(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xinmans/.local/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 959, in _cython_operation
    return cy_op.cython_operation(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xinmans/.local/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 645, in cython_operation
    self._disallow_invalid_ops(dtype, is_numeric)
  File "/home/xinmans/.local/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 257, in _disallow_invalid_ops
    raise TypeError(f"datetime64 type does not support {how} operations")
TypeError: datetime64 type does not support sum operations
Successfully created Absolute Gamma Exposure and Gamma Profile Charts!
Closing gammaCalculator.sh...

```

 less modules/spx_quotedata.csv 

```

S&P 500 INDEX,Last: 5722.2598,Change:  -10.6702
Date: 26 September 2024 at 05:55 GMT-4,Bid: 5687.8398,Ask: 5772.3999,Size: 1*1,Volume: 0
Expiration Date,Calls,Last Sale,Net,Bid,Ask,Volume,IV,Delta,Gamma,Open Interest,Strike,Puts,Last Sale,Net,Bid,Ask,Volume,IV,Delta,Gamma,Open Interest
Wed Sep 25 2024,SPXW240925C02200000,0,0,3510.5,3530.7,0,0,0,0,0,2200.00,SPXW240925P02200000,0,0,0,0.05,0,0,0,0,0
Wed Sep 25 2024,SPXW240925C02400000,0,0,3309.1,3330.3,0,0,0,0,0,2400.00,SPXW240925P02400000,0.05,0,0,0.05,0,0,0,0,3
Wed Sep 25 2024,SPXW240925C02600000,0,0,3109.3,3130.3,0,0,0,0,0,2600.00,SPXW240925P02600000,0.05,0,0,0.05,0,0,0,0,216
Wed Sep 25 2024,SPXW240925C02800000,2806.64,0,2909.9,2933.2,0,0,0,0,200,2800.00,SPXW240925P02800000,0.05,0,0,0.05,0,0,0,0,415
Wed Sep 25 2024,SPXW240925C03000000,0,0,2709,2733,0,0,0,0,0,3000.00,SPXW240925P03000000,0.05,0,0,0.05,0,0,0,0,45
Wed Sep 25 2024,SPXW240925C03200000,0,0,2509,2533,0,0,0,0,0,3200.00,SPXW240925P03200000,0.08,0,0,0.05,0,0,0,0,253

```

what‘s wrong？

**Comment by phammings** [comment]
I fixed the issue. I had to exclude the datetime64 columns before performing any summation or mathematical operations in groupby. So I fixed line 87 of modules/main.py

`
dfAgg = df.groupby(['StrikePrice']).sum(numeric_only=True)
`
